#!/usr/bin/env python
import os

import responses

from v2raycli.entry import v2raycli

_RESPONSE_TOML = os.path.join(os.path.dirname(__file__), 'responses.toml')


@responses.activate
def v2raycli_with_fake_response():
    responses._add_from_file(_RESPONSE_TOML)
    v2raycli()
    responses.reset()


if __name__ == '__main__':
    v2raycli_with_fake_response()
